// Code generated by protoc-gen-go from "btree.proto"
// DO NOT EDIT!

package btree

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type BtreeMetaData struct {
	Root             *int32  `protobuf:"varint,1,opt,name=root" json:"root,omitempty"`
	FirstLeaf        *int32  `protobuf:"varint,2,opt,name=first_leaf" json:"first_leaf,omitempty"`
	LastLeaf         *int32  `protobuf:"varint,3,opt,name=last_leaf" json:"last_leaf,omitempty"`
	LastNode         *int32  `protobuf:"varint,4,opt,name=last_node" json:"last_node,omitempty"`
	LeafCount        *int32  `protobuf:"varint,5,opt,name=leaf_count" json:"leaf_count,omitempty"`
	NodeCount        *int32  `protobuf:"varint,6,opt,name=node_count" json:"node_count,omitempty"`
	LeafMax          *int32  `protobuf:"varint,7,opt,name=leaf_max" json:"leaf_max,omitempty"`
	NodeMax          *int32  `protobuf:"varint,8,opt,name=node_max" json:"node_max,omitempty"`
	FreeList         []int32 `protobuf:"varint,9,rep,name=free_list" json:"free_list,omitempty"`
	Size             *uint32 `protobuf:"varint,10,opt,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BtreeMetaData) Reset()         { *this = BtreeMetaData{} }
func (this *BtreeMetaData) String() string { return proto.CompactTextString(this) }

type NodeMetaData struct {
	Id               *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Father           *int32   `protobuf:"varint,2,opt,name=father" json:"father,omitempty"`
	Childrens        []int32  `protobuf:"varint,3,rep,name=childrens" json:"childrens,omitempty"`
	Keys             [][]byte `protobuf:"bytes,4,rep,name=keys" json:"keys,omitempty"`
	Removed          *bool    `protobuf:"varint,5,opt,name=removed" json:"removed,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *NodeMetaData) Reset()         { *this = NodeMetaData{} }
func (this *NodeMetaData) String() string { return proto.CompactTextString(this) }

type LeafMetaData struct {
	Id               *int32            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Father           *int32            `protobuf:"varint,2,opt,name=father" json:"father,omitempty"`
	Next             *int32            `protobuf:"varint,3,opt,name=next" json:"next,omitempty"`
	Prev             *int32            `protobuf:"varint,4,opt,name=prev" json:"prev,omitempty"`
	Records          []*RecordMetaData `protobuf:"bytes,8,rep,name=records" json:"records,omitempty"`
	Removed          *bool             `protobuf:"varint,5,opt,name=removed" json:"removed,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *LeafMetaData) Reset()         { *this = LeafMetaData{} }
func (this *LeafMetaData) String() string { return proto.CompactTextString(this) }

type RecordMetaData struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RecordMetaData) Reset()         { *this = RecordMetaData{} }
func (this *RecordMetaData) String() string { return proto.CompactTextString(this) }

func init() {
}
